//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProtiPol
{
    using System;
    using System.Collections.Generic;
    
    public partial class Protipol
    {
        public string Mesto { get; set; }
        public string Poledník { get; set; }
        public string Rovník { get; set; }
        public string PoledníkData { get; set; }
        public string RovníkData { get; set; }
    }
}
